# Generated by Django 4.1.4 on 2022-12-08 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('school_address', models.CharField(max_length=250)),
                ('cac_reg_number', models.BigIntegerField()),
                ('school_email', models.EmailField(max_length=254)),
                ('school_phone_number', models.BigIntegerField()),
                ('school_logo', models.FileField(default='', upload_to='img')),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('local_govt_area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('owner_full_name', models.CharField(max_length=250)),
                ('owner_phone_number', models.BigIntegerField()),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_address', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('religion', models.CharField(max_length=50)),
                ('isDisabled', models.BooleanField(blank=True, null=True)),
                ('disability', models.CharField(blank=True, max_length=200, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('sports', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_school', models.CharField(max_length=250)),
                ('school_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.school')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('title', models.CharField(max_length=3)),
                ('full_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('contact_address', models.CharField(max_length=250)),
                ('religion', models.CharField(max_length=50)),
                ('local_govt_area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(max_length=150)),
                ('amount_owed', models.FloatField()),
                ('academic_session', models.DateField(unique_for_year=True)),
                ('parent_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.parent')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.school')),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Contention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('proof', models.FileField(upload_to='img')),
                ('parent_contending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.parent')),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student')),
            ],
        ),
    ]
